### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/modulo-3-evaluacion-intermedia-mercarf#1]
Buen trabajo @mercarf !

### Algunas pistas para acabarlo:

- [x] Este id no nos aporta nada aquí https://github.com/Adalab/modulo-3-evaluacion-intermedia-mercarf/blob/master/src/components/PokeList.js#L7
- [x] Debemos usar el id dentro de la key https://github.com/Adalab/modulo-3-evaluacion-intermedia-mercarf/blob/master/src/components/PokeList.js#L7

- Muy bien por pintar las evoluciones
- Muy bien por usar propTypes!!!

### Cuando tengas esto si quieres puedes:

1. Añadir un click a Pokemon que: marca o desmarca el pokemon como favorito en el array del estado de App.
1. Pasar este dato al componente Pokemon por props
1. Pintar Pokemon con otros estilos cuando por props nos llegue la info de que el pokemon es favorito

Si tienes cualquier duda, avisa!

Al turrón!!!

**Comment by mercarf** [comment]
He corregido el id.
Como comentario, he utilizado Default props, pero no propTypes, tengo que usar propTypes?
Los favoritos tengo que dedicarle más tiempo, a ver si lo saco antes de la evaluación.

**Comment by mercarf** [comment]
He empezado a plantear los favoritos en una rama nueva "fav", pero me pasa algo raro, y es que solo los pinta cuando selecciono varios y quito uno.. no llego a encontrar el por qué.
